#!/bin/sh

set -e

case $1 in
	remove|purge)
		if [ -x /etc/init.d/magnetodb ]; then
			invoke-rc.d magnetodb stop || true
		fi
		;;
esac


# Automatically added by dh_python2:
if which pyclean >/dev/null 2>&1; then
	pyclean -p magnetodb 
else
	dpkg -L magnetodb | grep \.py$ | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi

# End automatically added section

